embeddings {
  tensor_name: "embedding:0"
  metadata_path: "E:\\\345\267\245\344\275\234\346\226\207\344\273\266\\CODE\\LearnTF\\projector/projector/metadata.tsv"
  sprite {
    image_path: "E:\\\345\267\245\344\275\234\346\226\207\344\273\266\\CODE\\LearnTF\\projector/data/mnist_10k_sprite.png"
    single_image_dim: 28
    single_image_dim: 28
  }
}
